workflows:
  flutter-workflow:
    name: Build Flutter App
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      # 1) Install Pub dependencies
      - name: Install dependencies
        script: flutter pub get

      # 2) Generate app icons using flutter_launcher_icons
      - name: Generate app icons
        script: flutter pub run flutter_launcher_icons:main

      # 3) Clean any stale build outputs
      - name: Clean previous build artifacts
        script: |
          flutter clean
          rm -rf android/app/build

      # 4) Give Gradle more heap (4.5 GB) to avoid splitter OOM
      - name: Ensure Gradle JVM args
        script: |
          grep -qxF 'org.gradle.jvmargs=-Xmx4608m' android/gradle.properties \
            || echo 'org.gradle.jvmargs=-Xmx4608m' >> android/gradle.properties

      # 5) Build the release APK
      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
