workflows:
  flutter-workflow:
    name: Build Flutter App
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
#    publishing:
#      email:
#        recipients:
#          - your-mzaziforex@gmail.com
